// src/lib/types.ts

/** User profile collected during onboarding */
export interface UserProfile {
  bodyWeight: number; // kg
  goalWeight?: number | null; // target weight (kg) if applicable
  height?: number; // cm
  fitnessGoal: string; // e.g. 'Bulk', 'Cut', 'Strength', 'Aesthetics'
  gymExperience: 'Beginner' | 'Intermediate' | 'Advanced';
  workoutDays: number; // days per week
  muscleGroupsPerDay: '1 Muscle' | '2 Muscles' | 'Full Body';
  musclePriorities: string[]; // preferred muscles
}

/** One split option generated by the AI */
export interface SplitOption {
  id: string; // unique id
  name: string; // e.g. "Push/Pull/Legs (6‑day)"
  days: string[][]; // array of days, each day is an array of muscle groups
  volumeInfo: string; // description of set/rep scheme
  cardioInfo: string; // cardio recommendation summary
  calorieTarget: number; // daily calories to burn (kcal)
  difficulty: 'Easy' | 'Medium' | 'Hard';
  explanation: string; // why this split suits the user
}

/** Cardio recommendation */
export interface CardioPlan {
  type: 'Running' | 'Walking' | 'Cycling' | 'Stairmaster' | 'Elliptical';
  speedKmh?: number;
  incline?: number;
  durationMin: number;
  estimatedKcal: number;
}

/** Full workout plan for a day */
export interface WorkoutPlanDay {
  dayIndex: number;
  exercises: ExercisePlan[];
  cardio?: CardioPlan;
}

/** Exercise prescription */
export interface ExercisePlan {
  name: string;
  sets: number;
  reps: number;
  weight: number; // recommended starting weight
  unit: string; // e.g. 'kg' or 'lb'
}

/** Feedback record for weight adjustments */
export interface WeightFeedback {
  exerciseName: string;
  userWeight: number;
  adjustedWeight: number;
  date: string; // ISO date
}
